In [17]:
import torch
from datasets import load_dataset

dataset = load_dataset('mlfoundations/dclm-baseline-1.0', split='train', streaming=True)
shuffled_dataset = dataset.shuffle(seed=42, buffer_size=10_000)
keep_columns = ['metadata', 'text']
shuffled_dataset = shuffled_dataset.remove_columns([col for col in shuffled_dataset.column_names if col not in keep_columns])

Resolving data files:   0%|          | 0/27838 [00:00<?, ?it/s]

In [18]:
dataloader = torch.utils.data.DataLoader(shuffled_dataset, num_workers=4)

In [19]:
type(shuffled_dataset)

datasets.iterable_dataset.IterableDataset

In [29]:
from tqdm import tqdm
dataset_iterator = iter(shuffled_dataset)
liste = []
for i in tqdm(range(5000), dynamic_ncols=True):
    liste.append(next(dataset_iterator)['text'])

100%|██████████| 5000/5000 [00:08<00:00, 597.45it/s] 


In [31]:
from transformers import AutoTokenizer

model_id = "allenai/OLMo-2-1124-7B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

In [42]:
tokens = tokenizer(liste[0])['input_ids']

detokenized = tokenizer.batch_decode(tokens)
print("".join(detokenized))

Skip to definition.

Noun: vestry  ves-tree
  1. In the Protestant Episcopal Church: a committee elected by the congregation to work with the churchwardens in managing the temporal affairs of the church
  2. A room in a church where sacred vessels and vestments are kept or meetings are held
    - sacristy

Derived forms: vestries

Type of: commission, committee, room

Part of: church, church building

Encyclopedia: Vestry


tensor([[ 0.0915, -0.0590]], grad_fn=<MmBackward0>)

tensor([[ 2.,  1.,  1.],
        [ 0., -8., -2.],
        [ 0.,  0.,  1.]], grad_fn=<MmBackward0>)
tensor([[ 2.,  0.,  0.],
        [ 1., -8.,  0.],
        [ 1., -2.,  1.]], grad_fn=<PermuteBackward0>)


tensor([[  6., -10.,   1.],
        [-10.,  68.,  -2.],
        [  1.,  -2.,   1.]], grad_fn=<MmBackward0>)